### ISSUE TITLE
MongoDB error: "MongoError: language override unsupported: cs"

### ISSUE THREAD

**Issue by burningtree** [wingbotai/wingbot#4]
Zdravim,

Po upgradu MongoDB databaze na 4.2.2 nam chatbot zacal failovat a hlasi tento bug.

Nejak nemuzeme prijit na zdroj, kde se tam ten overrite posila, pomuzete?

```
error MongoError: language override unsupported: cs 
error         at Function.create (/corn/chatbot-v2/source/node_modules/mongodb/lib/core/error.js:44:12) 
error         at toError (/corn/chatbot-v2/source/node_modules/mongodb/lib/utils.js:150:22) 
error         at /corn/chatbot-v2/source/node_modules/mongodb/lib/operations/common_functions.js:373:39 
error         at /corn/chatbot-v2/source/node_modules/mongodb/lib/core/connection/pool.js:420:18 
error         at processTicksAndRejections (internal/process/task_queues.js:75:11) { 
error       driver: true, 
error       name: 'MongoError', 
error       index: 0, 
error       code: 17262, 
error       errmsg: 'language override unsupported: cs', 
error       [Symbol(mongoErrorContextSymbol)]: {} 
error     } { 
error       timestamp: 1582792814726, 
error       sender: { id: '6632987142442993013' }, 
error       message: { 
error         text: '/shiftRemoveConfirm', 
error         quick_reply: { 
error           payload: '{"action":"/shiftRemoveConfirm","data":{"type":"remove","shift":"5e4fd3d21390cb54e563c6ff"}}' 
error         } 
error       } 
error     } 
```

**Comment by davidmenger** [comment]
Chyba je spojena s fulltext indexem s definovanou property language override, viz: https://docs.mongodb.com/manual/tutorial/specify-language-for-text-index/

Wingbot pouziva fulltext jen nad states, ale bez tohoto nastaveni, viz https://github.com/wingbotai/wingbot-mongodb/blob/a763013266b8b2f1c38837bf210513218cb3fbf0/src/StateStorage.js#L59

Z callstacku uplne nevidim puvodce teto hlasky, ale pusobi to na me jako volani do kolekce, ktera ma na sobe definovany prave takovy index. Muze to byt i nejaka mimo ty, ktere primo pouziva wingbot.

Muzete overit, na kterych kolekcich mate nastavene textove indexy a jestli nahodou tuto property nemaji nastavenou?

**Comment by burningtree** [comment]
Dekuji za pomoc, vyreseno. Problem byl diky spatnemu vstupnimu objektu.
